export const quizQuestions = [
  {
    id: "ageRange",
    title: "Which age range best describes you?",
    description: "This helps us tailor examples and risk framing.",
    type: "choice",
    options: ["18-29", "30-39", "40-49", "50-59", "60+"],
  },
  {
    id: "monthlyIncome",
    title: "What is your monthly income?",
    description: "Use your usual take-home amount.",
    type: "choice",
    options: ["Below $3,000", "$3,000-$5,999", "$6,000-$9,999", "$10,000+"],
  },
  {
    id: "employmentType",
    title: "How do you mainly earn your income?",
    description: "Different income types can face different disruption risks.",
    type: "choice",
    options: ["Full-time employee", "Self-employed", "Business owner", "Freelancer / gig worker"],
  },
  {
    id: "dependents",
    title: "How many people depend on your income?",
    description: "Include children, parents, or a partner who relies on your earnings.",
    type: "choice",
    options: ["0", "1", "2", "3+"],
  },
  {
    id: "savingsMonths",
    title: "How many months of expenses could your savings cover today?",
    description: "Think of emergency savings only, not investments you would rather not touch.",
    type: "choice",
    options: ["Less than 3 months", "3 to 6 months", "More than 6 months"],
  },
  {
    id: "hospitalCoverage",
    title: "Do you currently have hospital insurance coverage?",
    description: "Include employer or personal policies if you know you are covered.",
    type: "choice",
    options: ["Yes", "No", "Unsure"],
  },
  {
    id: "incomeProtection",
    title: "Do you have income protection in place?",
    description: "This refers to coverage that helps replace income if you cannot work.",
    type: "choice",
    options: ["Yes", "Partial", "No"],
  },
  {
    id: "financialConcern",
    title: "What is your biggest financial concern right now?",
    description: "We use this to personalise your guidance.",
    type: "choice",
    options: [
      "Paying bills if income stops",
      "Hospital and medical costs",
      "Supporting my family",
      "I am not sure what gaps I have",
    ],
  },
  {
    id: "planningConfidence",
    title: "How confident do you feel about your current financial safety net?",
    description: "Your answer helps us frame the results and next steps.",
    type: "choice",
    options: ["Very confident", "Somewhat confident", "Not very confident", "Not confident at all"],
  },
];
